name: "Push to cachix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: moxidle
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build --no-link --print-out-paths > /tmp/paths
    - run: cat /tmp/paths | cachix push moxidle
